DineTime/Models/Reservation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DineTime.Models
{
    public partial class Reservation
    {
        [Key]
        public int ReservationId { get; set; }
        public int RestaurantId { get; set; }
        public int ClientId { get; set; }
        public TimeSpan? ReservationTime { get; set; }
        public DateTime ReservationDate { get; set; }
        public int NumberInParty { get; set; }

        public virtual Client? Client { get; set; }
        public virtual Restaurant? Restaurant { get; set; }
    }
}

DineTime/Controllers/ClientsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DineTime.Models;

namespace DineTime.Controllers
{
    public class ClientsController : Controller
    {
        private readonly DineTimeDbContext _context;

        public ClientsController(DineTimeDbContext context)
        {
            _context = context;
        }

        // GET: Clients
        public async Task<IActionResult> Index()
        {
            return View(await _context.Clients.ToListAsync());
        }

        // GET: Clients/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients
                .FirstOrDefaultAsync(m => m.ClientId == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // GET: Clients/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClientId,FirstName,LastName,PhoneNumber")] Client client)
        {
            if (ModelState.IsValid)
            {
                _context.Add(client);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients.FindAsync(id);
            if (client == null)
            {
                return NotFound();
            }
            return View(client);
        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ClientId,FirstName,LastName,PhoneNumber")] Client client)
        {
            if (id != client.ClientId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(client);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientExists(client.ClientId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients
                .FirstOrDefaultAsync(m => m.ClientId == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var client = await _context.Clients.FindAsync(id);
            _context.Clients.Remove(client);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClientExists(int id)
        {
            return _context.Clients.Any(e => e.ClientId == id);
        }
    }
}

DineTime/Controllers/ReservationsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DineTime.Models;

namespace DineTime.Controllers
{
    public class ReservationsController : Controller
    {
        private readonly DineTimeDbContext _context;

        public ReservationsController(DineTimeDbContext context)
        {
            _context = context;
        }

        public IActionResult FieriReservation()
        {

            ViewData["ClientId"] = new SelectList(_context.Clients, "ClientId", "ClientId");
            ViewData["RestaurantId"] = new SelectList(_context.Restaurants, "RestaurantId", "RestaurantId");
            return View();
        }
        public IActionResult SantanaReservation()
        {

            ViewData["ClientId"] = new SelectList(_context.Clients, "ClientId", "ClientId");
            ViewData["RestaurantId"] = new SelectList(_context.Restaurants, "RestaurantId", "RestaurantId");
            return View();
        }

        public IActionResult LaCasaReservation()
        {

            ViewData["ClientId"] = new SelectList(_context.Clients, "ClientId", "ClientId");
            ViewData["RestaurantId"] = new SelectList(_context.Restaurants, "RestaurantId", "RestaurantId");
            return View();
        }


        // GET: Reservations
        public async Task<IActionResult> Index()
        {
            var dineTimeDbContext = _context.Reservations.Include(r => r.Client).Include(r => r.Restaurant);
            return View(await dineTimeDbContext.ToListAsync());
        }

        // GET: Reservations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservations
                .Include(r => r.Client)
                .Include(r => r.Restaurant)
                .FirstOrDefaultAsync(m => m.ReservationId == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        // GET: Reservations/Create
        public IActionResult Create()
        {
            ViewData["ClientId"] = new SelectList(_context.Clients, "ClientId", "ClientId");
            ViewData["RestaurantId"] = new SelectList(_context.Restaurants, "RestaurantId", "RestaurantId");

            return View();
        }

        // POST: Reservations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ReservationId,RestaurantId,ClientId,ReservationTime,ReservationDate,NumberInParty")] Reservation reservation)
        {

            reservation.ReservationTime = reservation.ReservationDate.TimeOfDay;




            if (ModelState.IsValid)
            {
                _context.Add(reservation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["ClientId"] = new SelectList(_context.Clients, "ClientId", "ClientId");
            ViewData["RestaurantId"] = new SelectList(_context.Restaurants, "RestaurantId", "RestaurantId");
            return View(reservation);
            

        }

        // GET: Reservations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservations.FindAsync(id);
            if (reservation == null)
            {
                return NotFound();
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "ClientId", "ClientId", reservation.ClientId);
            ViewData["RestaurantId"] = new SelectList(_context.Restaurants, "RestaurantId", "RestaurantId", reservation.RestaurantId);
            return View(reservation);
        }

        // POST: Reservations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ReservationId,RestaurantId,ClientId,ReservationTime,ReservationDate,NumberInParty")] Reservation reservation)
        {
            if (id != reservation.ReservationId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reservation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReservationExists(reservation.ReservationId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "ClientId", "ClientId", reservation.ClientId);
            ViewData["RestaurantId"] = new SelectList(_context.Restaurants, "RestaurantId", "RestaurantId", reservation.RestaurantId);
            return View(reservation);
        }

        // GET: Reservations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservations
                .Include(r => r.Client)
                .Include(r => r.Restaurant)
                .FirstOrDefaultAsync(m => m.ReservationId == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        public IActionResult ReservationError()
        {
            return View();
        }

        // POST: Reservations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reservation = await _context.Reservations.FindAsync(id);
            _context.Reservations.Remove(reservation);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReservationExists(int id)
        {
            return _context.Reservations.Any(e => e.ReservationId == id);
        }
    }
}

DineTime/Views/Reservations/Create.cshtml
@model DineTime.Models.Reservation

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Reservation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RestaurantId" class="control-label"></label>
                <select asp-for="RestaurantId" class ="form-control" asp-items="ViewBag.RestaurantId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ClientId" class="control-label"></label>
                <select asp-for="ClientId" class ="form-control" asp-items="ViewBag.ClientId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ReservationTime" class="control-label"></label>
                <input asp-for="ReservationTime" class="form-control" />
                <span asp-validation-for="ReservationTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReservationDate" class="control-label"></label>
                <input asp-for="ReservationDate" class="form-control" />
                <span asp-validation-for="ReservationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberInParty" class="control-label"></label>
                <input asp-for="NumberInParty" class="form-control" />
                <span asp-validation-for="NumberInParty" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DineTime/Views/Reservations/Delete.cshtml
@model DineTime.Models.Reservation

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Reservation</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReservationTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReservationTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReservationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReservationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberInParty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberInParty)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Client)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Client.ClientId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Restaurant)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Restaurant.RestaurantId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ReservationId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DineTime/Views/Reservations/Details.cshtml
@model DineTime.Models.Reservation

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Reservation</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReservationTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReservationTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReservationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReservationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberInParty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberInParty)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Client)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Client.ClientId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Restaurant)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Restaurant.RestaurantId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ReservationId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DineTime/Views/Reservations/Edit.cshtml
@model DineTime.Models.Reservation

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Reservation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ReservationId" />
            <div class="form-group">
                <label asp-for="RestaurantId" class="control-label"></label>
                <select asp-for="RestaurantId" class="form-control" asp-items="ViewBag.RestaurantId"></select>
                <span asp-validation-for="RestaurantId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientId" class="control-label"></label>
                <select asp-for="ClientId" class="form-control" asp-items="ViewBag.ClientId"></select>
                <span asp-validation-for="ClientId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReservationTime" class="control-label"></label>
                <input asp-for="ReservationTime" class="form-control" />
                <span asp-validation-for="ReservationTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReservationDate" class="control-label"></label>
                <input asp-for="ReservationDate" class="form-control" />
                <span asp-validation-for="ReservationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberInParty" class="control-label"></label>
                <input asp-for="NumberInParty" class="form-control" />
                <span asp-validation-for="NumberInParty" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DineTime/Views/Reservations/FieriReservation.cshtml
@model DineTime.Models.Reservation


@{
    ViewData["Title"] = "Make a Reservation";
}

<header>
    <nav class="navbar">
        <a id="logo-link" class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
            <img id="dinetime-logo" alt="Logo" src="~/contents/svg_assets/logo_icon.svg" />
        </a>
    </nav>
</header>


<div class="container" id="testres">
    <div class="row">
    <div class="col">
        <figure>
            <img src="~/contents/images/burgle2.png" alt="">
        </figure>
        <ul id="left-group" class="list-group" name="res-fillout">
            <li class="list-group-item" id="res-header">
                Make a reservation
            </li>
            <li class="list-group-item">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    @Html.Hidden("RestaurantId", 3)
                    
                    @Html.Hidden("ClientId", 1)
                    
                    <div id="date-time-div" class="form-group">
                        <label asp-for="ReservationDate" class="control-label">Date & Time</label>
                        <input asp-for="ReservationDate" class="form-control" />
                        <span asp-validation-for="ReservationDate" class="text-danger" ></span>
                    </div>
                    <div id="party-size-div" class="form-group">
                        <label asp-for="NumberInParty" class="control-label">Party Size</label>
                        <input asp-for="NumberInParty" class="form-control" />
                        <span asp-validation-for="NumberInParty" class="text-danger"></span>
                    </div>
                    <div id="create-btn" class="form-group">
                        <input id="sub-res" type="submit" value="Reserve Now" class="btn btn-primary" />
                    </div>
                </form>
            </li>
        </ul>
        <br>
    </div>
    <div class="col">
        <div id="whole-card" class="card">
            <h3 id="res-name" class="card-title">Fieri's Bar & Grill <span id="bkmrk"> <img src="~/contents/svg_assets/bookmark_icon.svg" alt=""></span></h3>
            <h5 class="card-subtitle mb-2 text-muted">349 Monmouth Ave N. Monmouth OR, 97361</h5>
            <p></p>
            <h6 class="card-subtitle "> 
                <span>
                    <img src="~/contents/svg_assets/cutlery_icon.svg" alt="">
                </span> 
                Steakhouse / Grill  </h6>
            <p></p>
            <ul class="list-group list-group-horizontal list-group-flush">
                <li class="list-group-item"><h5 id="overview" style="color:#B5464C; text-decoration:underline;">Overview</h5></li>
                <li class="list-group-item"><h5 class="text-muted" id="photos">Photos</h5></li>
                <li class="list-group-item"><h5 class="text-muted" id="menu">Menu</h5></li>
                <li class="list-group-item"><h5 class="text-muted" id="reviews">Reviews</h5></li>
            </ul>
            <p></p>
            <div id="overview-card" class="card">
                <h3 id="stars" class="card-title">★★★★☆</h3>
                <span></span>
                <h5  id="ov-sub" class="card-subtitle">
                    <span>
                        <img src="~/contents/svg_assets/review_icon.svg" alt="">
                    </span>

                    <span> </span>
                    <span> </span>

                    151 Reviews</h5>

                <p></p>

                <h4  id="ov-sub"  class="card-subtitle">
                    Most recent review
                </h4>

                <h5  id="ov-subr"  class="card-subtitle">
                    "Great burgers and a huge selection of drinks, try their ribeye!" - George W.
                </h5>

                <p></p>

                <h4  id="ov-sub"  class="card-subtitle">
                    Pricing
                </h4>
                <h5  id="ov-sub"  class="card-subtitle">
                    <span>
                        <img src="~/contents/svg_assets/money_icon.svg" alt="">
                    </span>

                    <span> </span>
                    <span> </span>

                    $12 to $50

                </h5>

                <p></p>

                <h4  id="ov-sub"  class="card-subtitle">
                    Popular Dishes
                </h4>

                <ul class="list-group list-group-horizontal list-group-flush">
                    <li class="list-group-item" >Western Deluxe Burger</li>
                    <li class="list-group-item" >Honey-glazed NY Strip</li>
                    <li class="list-group-item" >Bloomin' Onion</li>
                </ul>

                <br>

                <h4  id="ov-sub"  class="card-subtitle">
                    Common Tags
                </h4>

                <ul class="list-group list-group-horizontal">
                    <li class="list-group-item" > Spacious </li>
                    <li class="list-group-item" > Sports </li>
                    <li class="list-group-item" > Country </li>
                </ul>

            </div>

        </div>
    </div>
    </div>
</div>

<script src="~/wwwroot/js/site.js"></script>

DineTime/Views/Reservations/Index.cshtml
@model IEnumerable<DineTime.Models.Reservation>

@{
    ViewData["Title"] = "Index";
}

<h1>Reservations</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ReservationTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReservationDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumberInParty)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Client)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Restaurant)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ReservationTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReservationDate.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberInParty)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Client.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Restaurant.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ReservationId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ReservationId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ReservationId">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>

<a asp-controller="Clients" asp-action="Index">Client Index</a>

DineTime/Views/Reservations/LaCasaReservation.cshtml
@model DineTime.Models.Reservation

@{
    ViewData["Title"] = "Make a Reservation";
}

<header>
    <nav class="navbar">
        <a id="logo-link" class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
            <img id="dinetime-logo" alt="Logo" src="~/contents/svg_assets/logo_icon.svg" />
        </a>
    </nav>
</header>


<div class="container" id="testres">
    <div class="row">
    <div class="col">
        <figure>
            <img src="~/contents/images/tacos.png" alt="">
        </figure>
        <ul id="left-group" class="list-group" name="res-fillout">
            <li class="list-group-item" id="res-header">
                Make a reservation
            </li>
            <li class="list-group-item">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    @Html.Hidden("RestaurantId", 2)
                    
                    @Html.Hidden("ClientId", 1)
                    
                    <div id="date-time-div" class="form-group">
                        <label asp-for="ReservationDate" class="control-label">Date & Time</label>
                        <input asp-for="ReservationDate" class="form-control" />
                        <span asp-validation-for="ReservationDate" class="text-danger" ></span>
                    </div>
                    <div id="party-size-div" class="form-group">
                        <label asp-for="NumberInParty" class="control-label">Party Size</label>
                        <input asp-for="NumberInParty" class="form-control" />
                        <span asp-validation-for="NumberInParty" class="text-danger"></span>
                    </div>
                    <div id="create-btn" class="form-group">
                        <input id="sub-res" type="submit" value="Reserve Now" class="btn btn-primary" />
                    </div>
                </form>
            </li>
        </ul>
        <br>

    </div>
    <div class="col">
        <div id="whole-card" class="card">
            <h3 id="res-name" class="card-title"> La Casa Tacos <span id="bkmrk"> <img src="~/contents/svg_assets/bookmark_icon.svg" alt=""></span></h3>
            <h5 class="card-subtitle mb-2 text-muted">348 Monmouth Ave N. Monmouth OR, 97361</h5>
            <p></p>
            <h6 class="card-subtitle "> 
                <span>
                    <img src="~/contents/svg_assets/cutlery_icon.svg" alt="">
                </span> 
                Taqueria / Authenic Mexican  </h6>
            <p></p>
            <ul class="list-group list-group-horizontal list-group-flush">
                <li class="list-group-item"><h5 id="overview" style="color:#B5464C; text-decoration:underline;">Overview</h5></li>
                <li class="list-group-item"><h5 class="text-muted" id="photos">Photos</h5></li>
                <li class="list-group-item"><h5 class="text-muted" id="menu">Menu</h5></li>
                <li class="list-group-item"><h5 class="text-muted" id="reviews">Reviews</h5></li>
            </ul>
            <p></p>
            <div id="overview-card" class="card">
                <h3 id="stars" class="card-title">★★★★★</h3>
                <span></span>
                <h5  id="ov-sub" class="card-subtitle">
                    <span>
                        <img src="~/contents/svg_assets/review_icon.svg" alt="">
                    </span>

                    <span> </span>
                    <span> </span>

                    76 Reviews</h5>

                <p></p>

                <h4  id="ov-sub"  class="card-subtitle">
                    Most recent review
                </h4>

                <h5  id="ov-subr"  class="card-subtitle">
                    "They have the best tacos ever, my favorite would probably be
                    the carne asada tacos." - Olivia R.
                </h5>

                <p></p>

                <h4  id="ov-sub"  class="card-subtitle">
                    Pricing
                </h4>
                <h5  id="ov-sub"  class="card-subtitle">
                    <span>
                        <img src="~/contents/svg_assets/money_icon.svg" alt="">
                    </span>

                    <span> </span>
                    <span> </span>

                    $5 to $18

                </h5>

                <p></p>

                <h4  id="ov-sub"  class="card-subtitle">
                    Popular Dishes
                </h4>

                <ul class="list-group list-group-horizontal list-group-flush">
                    <li class="list-group-item" >Tacos de Lengua</li>
                    <li class="list-group-item" >Carne Asada Burrito</li>
                    <li class="list-group-item" >Sopes de Pollo</li>
                </ul>

                <br>

                <h4  id="ov-sub"  class="card-subtitle">
                    Common Tags
                </h4>

                <ul class="list-group list-group-horizontal">
                    <li class="list-group-item" > Quick Bite </li>
                    <li class="list-group-item" > Festive </li>
                    <li class="list-group-item" > Lively </li>
                    <li class="list-group-item" > Inexpensive </li>
                </ul>

            </div>

        </div>
    </div>
    </div>
</div>

<script src="~/wwwroot/js/site.js"></script>