DineTime/Controllers/HomeController.cs
using DineTime.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DineTime.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        
        public IActionResult TopRatedEats()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DineTime/Controllers/ReservationsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DineTime.Models;

namespace DineTime.Controllers
{
    public class ReservationsController : Controller
    {
        private readonly DineTimeDbContext _context;

        public ReservationsController(DineTimeDbContext context)
        {
            _context = context;
        }

        public IActionResult FieriReservation()
        {

            ViewData["ClientId"] = new SelectList(_context.Clients, "ClientId", "ClientId");
            ViewData["RestaurantId"] = new SelectList(_context.Restaurants, "RestaurantId", "RestaurantId");
            return View();
        }
        public IActionResult SantanaReservation()
        {

            ViewData["ClientId"] = new SelectList(_context.Clients, "ClientId", "ClientId");
            ViewData["RestaurantId"] = new SelectList(_context.Restaurants, "RestaurantId", "RestaurantId");
            return View();
        }

        public IActionResult LaCasaReservation()
        {

            ViewData["ClientId"] = new SelectList(_context.Clients, "ClientId", "ClientId");
            ViewData["RestaurantId"] = new SelectList(_context.Restaurants, "RestaurantId", "RestaurantId");
            return View();
        }


        // GET: Reservations
        public async Task<IActionResult> Index()
        {
            var dineTimeDbContext = _context.Reservations.Include(r => r.Client).Include(r => r.Restaurant);
            return View(await dineTimeDbContext.ToListAsync());
        }

        // GET: Reservations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservations
                .Include(r => r.Client)
                .Include(r => r.Restaurant)
                .FirstOrDefaultAsync(m => m.ReservationId == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        // GET: Reservations/Create
        public IActionResult Create()
        {
            ViewData["ClientId"] = new SelectList(_context.Clients, "ClientId", "ClientId");
            ViewData["RestaurantId"] = new SelectList(_context.Restaurants, "RestaurantId", "RestaurantId");

            return View();
        }

        // POST: Reservations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ReservationId,RestaurantId,ClientId,ReservationTime,ReservationDate,NumberInParty")] Reservation reservation)
        {

            reservation.ReservationTime = reservation.ReservationDate.TimeOfDay;




            if (ModelState.IsValid)
            {
                _context.Add(reservation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["ClientId"] = new SelectList(_context.Clients, "ClientId", "ClientId");
            ViewData["RestaurantId"] = new SelectList(_context.Restaurants, "RestaurantId", "RestaurantId");
            return View(reservation);
            

        }

        // GET: Reservations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservations.FindAsync(id);
            if (reservation == null)
            {
                return NotFound();
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "ClientId", "ClientId", reservation.ClientId);
            ViewData["RestaurantId"] = new SelectList(_context.Restaurants, "RestaurantId", "RestaurantId", reservation.RestaurantId);
            return View(reservation);
        }

        // POST: Reservations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ReservationId,RestaurantId,ClientId,ReservationTime,ReservationDate,NumberInParty")] Reservation reservation)
        {
            if (id != reservation.ReservationId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reservation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReservationExists(reservation.ReservationId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "ClientId", "ClientId", reservation.ClientId);
            ViewData["RestaurantId"] = new SelectList(_context.Restaurants, "RestaurantId", "RestaurantId", reservation.RestaurantId);
            return View(reservation);
        }

        // GET: Reservations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservations
                .Include(r => r.Client)
                .Include(r => r.Restaurant)
                .FirstOrDefaultAsync(m => m.ReservationId == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        public IActionResult ReservationError()
        {
            return View();
        }

        // POST: Reservations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reservation = await _context.Reservations.FindAsync(id);
            _context.Reservations.Remove(reservation);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReservationExists(int id)
        {
            return _context.Reservations.Any(e => e.ReservationId == id);
        }
    }
}

DineTime/Controllers/ReviewsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DineTime.Models;

namespace DineTime.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly DineTimeDbContext _context;

        public ReviewsController(DineTimeDbContext context)
        {
            _context = context;
        }

        // GET: Reviews
        public async Task<IActionResult> Index()
        {
            return View(await _context.Reviews.ToListAsync());
        }

        // GET: Reviews/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Reviews
                .FirstOrDefaultAsync(m => m.ReviewId == id);
            if (review == null)
            {
                return NotFound();
            }

            return View(review);
        }

        // GET: Reviews/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Reviews/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ReviewId,Rating,Comments")] Review review)
        {
            if (ModelState.IsValid)
            {
                _context.Add(review);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(review);
        }

        // GET: Reviews/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Reviews.FindAsync(id);
            if (review == null)
            {
                return NotFound();
            }
            return View(review);
        }

        // POST: Reviews/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ReviewId,Rating,Comments")] Review review)
        {
            if (id != review.ReviewId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(review);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReviewExists(review.ReviewId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(review);
        }

        // GET: Reviews/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Reviews
                .FirstOrDefaultAsync(m => m.ReviewId == id);
            if (review == null)
            {
                return NotFound();
            }

            return View(review);
        }

        // POST: Reviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var review = await _context.Reviews.FindAsync(id);
            _context.Reviews.Remove(review);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReviewExists(int id)
        {
            return _context.Reviews.Any(e => e.ReviewId == id);
        }
    }
}

DineTime/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<header>
    <nav class="navbar">
        <a id="logo-link" class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
            <img id="dinetime-logo" alt="Logo" src="~/contents/svg_assets/logo_icon.svg" />
        </a>
        <a id="top-rated-link" class="nav-link" asp-area="" asp-controller="Home" asp-action="TopRatedEats">Top Rated Eats</a>
        <a id="write-review-link" class="nav-link" asp-area="" asp-controller="Reviews" asp-action="Create">Write a Review</a>
    </nav>
</header>

<div id="search-block">

    <div id="form-row" class="row">

        <div class="input-group" id="date-request">
            <span class="input-group-text">
                <img src="~/contents/svg_assets/schedule_icon.svg" alt="">
            </span>
            <input type="date">
        </div>

        <div class="input-group" id="time-request">
            <span class="input-group-text">
                <img src="~/contents/svg_assets/clock_icon.svg" alt="">
            </span>
            <input type="time">
        </div>

        <div class="input-group" id="party-size">
            <span class="input-group-text">
                <img src="~/contents/svg_assets/person_icon.svg" alt="">
            </span>
            <input type="number" placeholder="2" min="1", max="12">
        </div>

        <div class="input-group" id="location-name">
            <span class="input-group-text" >
                <img src="~/contents/svg_assets/search_icon.svg" alt="">
            </span>
            <input type="search" placeholder="Location, Cuisine">
        </div>

        <div class="input-group" id="submit-form">
            <button id="submit-button" type="submit">Search!</button>
        </div>

</div>

<body>
    @for (int i = 0; i < 5; i++)
    {
        <br>
    }
    <div class="row">
        <div class="col-md-3">
            <h4>Restaurants Near You</h4>
        </div>
    </div>
    <br>
    <div class="container">
    <div class="row">
        <div class="col-lg-4">
            <div class="Restaurant1">
                <div class="restaurantName">
                    Fieri's Bar & Grill
                </div>
                <br>
                <div class="row">
                    <div class="col-sm-5">
                        <div class="restaurantImage">
                            <img id="bg-img" src="~/contents/images/burgle2.png" width="85" height="85">
                        </div>
                    </div>
                    <div class="col-sm-7">
                        <div class="restaurantType">
                            &#9733 &#9733 &#9733 &#9733 &#9734
                            <div class="reviewNum">
                                151 reviews
                            </div>
                            Steakhouse
                        </div>
                    </div>
                </div>
                <p></p>
                <a id="res-now-btn" asp-controller="Reservations" asp-action="FieriReservation">Reserve Now</a>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="Restaurant2">
                <div class="restaurantName">
                    La Casa Tacos
                </div>
                <br>
                <div class="row">
                    <div class="col-sm-5">
                        <div class="restaurantImage">
                            <img id="mexi-img" src="~/contents/images/tacos.png" width="85" height="85">
                        </div>
                    </div>
                    <div class="col-sm-7">
                        <div class="restaurantType">
                            &#9733 &#9733 &#9733 &#9733 &#9733
                            <div class="reviewNum">
                                76 reviews
                            </div>
                            Taqueria
                        </div>
                    </div>
                </div>
                <p></p>
                <a id="res-now-btn" asp-controller="Reservations" asp-action="LaCasaReservation">Reserve Now</a>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="Restaurant3">
                <div class="restaurantName">
                    Santana Sandwiches
                </div>
                <br>
                <div class="row">
                    <div class="col-sm-5">
                        <div class="restaurantImage">
                            <img id="ital-img" src="~/contents/images/santana_sandwich.png" width="85" height="85">
                        </div>
                    </div>
                    <div class="col-sm-7">
                        <div class="restaurantType">
                            &#9733 &#9733 &#9733 &#9733 &#9734
                            <div class="reviewNum">
                                58 reviews
                            </div>
                            Sandwich
                        </div>
                    </div>
                </div>
                <p></p>
                <a id="res-now-btn" asp-controller="Reservations" asp-action="SantanaReservation">Reserve Now</a>
            </div>
        </div>
    </div>
</div>
</body>

DineTime/Views/Home/TopRatedEats.cshtml
@{
    ViewData["Title"] = "Top Rated Page";
}

<header>
    <nav class="navbar">
        <a id="logo-link" class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
            <img id="dinetime-logo" alt="Logo" src="~/contents/svg_assets/logo_icon.svg" />
        </a>
    </nav>
</header>

<body>
    <div class="row">
        <div class="col-md-3">
            <h3>Current Top Rated Restaurants:</h3>
        </div>
    </div>
    <br>
    <div class="container">
    <div class="row">
        <div class="col-lg-4">
            <div class="h3">
                1st
            </div>
            <div class="Restaurant2">
                <div class="restaurantName">
                    La Casa Tacos
                </div>
                <br>
                <div class="row">
                    <div class="col-sm-5">
                        <div class="restaurantImage">
                            <img id="mexi-img" src="~/contents/images/tacos.png" width="85" height="85">
                        </div>
                    </div>
                    <div class="col-sm-7">
                        <div class="restaurantType">
                            &#9733 &#9733 &#9733 &#9733 &#9733
                            <div class="reviewNum">
                                76 reviews
                            </div>
                            Taqueria
                        </div>
                    </div>
                </div>
                <p></p>
                <a id="res-now-btn" asp-controller="Reservations" asp-action="LaCasaReservation">Reserve Now</a>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="h3">
                2nd
            </div>
            <div class="Restaurant1">
                <div class="restaurantName">
                    Fieri's Bar & Grill
                </div>
                <br>
                <div class="row">
                    <div class="col-sm-5">
                        <div class="restaurantImage">
                            <img id="bg-img" src="~/contents/images/burgle2.png" width="85" height="85">
                        </div>
                    </div>
                    <div class="col-sm-7">
                        <div class="restaurantType">
                            &#9733 &#9733 &#9733 &#9733 &#9734
                            <div class="reviewNum">
                                151 reviews
                            </div>
                            Steakhouse
                        </div>
                    </div>
                </div>
                <p></p>
                <a id="res-now-btn" asp-controller="Reservations" asp-action="FieriReservation">Reserve Now</a>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="h3">
                3rd
            </div>
            <div class="Restaurant3">
                <div class="restaurantName">
                    Santana Sandwiches
                </div>
                <br>
                <div class="row">
                    <div class="col-sm-5">
                        <div class="restaurantImage">
                            <img id="ital-img" src="~/contents/images/santana_sandwich.png" width="85" height="85">
                        </div>
                    </div>
                    <div class="col-sm-7">
                        <div class="restaurantType">
                            &#9733 &#9733 &#9733 &#9733 &#9734
                            <div class="reviewNum">
                                58 reviews
                            </div>
                            Sandwich
                        </div>
                    </div>
                </div>
                <p></p>
                <a id="res-now-btn" asp-controller="Reservations" asp-action="SantanaReservation">Reserve Now</a>
            </div>
        </div>
    </div>
</div>
</body>